import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex justify-center items-center min-h-screen bg-gray-500 bg-opacity-30">
          {children}
        </main>
      </body>
    </html>
  )
}
